import pygame
from time import sleep
from time import *
pygame.init()
print("Welcome to your free trial of Digital Bard.")
sleep(3)
print("I will present you with a series of choices that will ultimately result in a customized poem for you to hear at the end of your adventure.")
sleep(3)
print("This trial includes selections from all five of our premium genre paths, including our latest path, Total Chaos.")
sleep(3)
print("First, let's choose a performer for your poem.  I'll let each one of our nine sample narrators introduce himself and give a little demonstration.  All you need to do is type the number that corresponds with the performer of your choice and then press Enter.")
sleep(3)
print("Let's hear from Aloysius first.")
sleep(3)
print("Hi, I'm Aloysius, otherwise known as Narrator One.")
sleep(3)
print("If you must cross a course cross cow across a crowded cow crossing, cross the cross coarse cow across the crowded cow crossing carefully.")
sleep(3)
print("How much wood would a woodchuck chuck if a woodchuck could chuck wood?  He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.")
sleep(3)
print("Narrator Two here.  My name is Raistlin.")
sleep(3)
print("You know New York.  You need New York.  You know you need unique New York.")
sleep(3)
print("A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.")
sleep(3)
print("This is Reginald, Narrator Three.")
sleep(3)
print("The great Greek grape growers grow great Greek grapes.")
sleep(3)
print("Rubber baby buggy bumpers.")
sleep(3)
print("My name is Yaxamie, and I'm Narrator Four.")
sleep(3)
print("I slit the sheet.  The sheet I slit, and on the slitted sheet I sit.")
sleep(3)
print("Six sick hicks nick six slick bricks with picks and sticks.")
sleep(3)
print("I'm Narrator Five, Tasslehoff.")
sleep(3)
print("The sixth sick sheikh's sixth sheep's sick.")
sleep(3)
print("Linda Lou Lambert loves lemon lollipop lip gloss.")
sleep(3)
print("Thadian here, your Narrator Six.")
sleep(3)
print("Which wrist watches are Swiss wrist watches?")
sleep(3)
print("Rory the warrior and Roger the worrier were reared wrongly in a rural brewery.")
sleep(3)
print("This is Morgan, Narrator Seven.")
sleep(3)
print("One One was a race horse.  Two Two was one too.  One One won one race.  Two Two won one too.")
sleep(3)
print("A synonym for cinnamon is a cinnamon synonym.")
sleep(3)
print("Betty bought butter, but the butter was bitter, so Betty bought better butter to make the bitter butter better.")
sleep(3)
print("I'm Patrick, Narrator Eight.")
sleep(3)
print("I thought a thought, but the thought I thought wasn't the thought I thought I thought.  If the thought I thought had been the thought I thought, i wouldn't have thought I thought.")
sleep(3)
print("Susie works in a shoeshine shop.  where she shines, she sits, and where she sits, she shines.")
sleep(3)
print("Last but not least, I'm Narrator Nine, Vincent.  Nice to meet you, adventurer.")
sleep(3)
print("Brisk, brave brigadiers brandished broad, bright blades, blunderbusses, and bludgeons, balancing them badly.")
sleep(3)
print("Lesser leather never weathered wetter weather better.")
sleep(3)
print("Fresh French fried fly fritters.")
sleep(3)
print("Type the number of your choice and press Enter:")
sleep(3)
print("Please choose from the provided options.")
sleep(3)
print("You have selected Narrator One, Aloysius.")
sleep(3)
print("You have selected Narrator Two, Raistlin.")
sleep(3)
print("This is truly the highlight of my day, and for the record, I am not one of the mages of Holin'dorf.")
sleep(3)
print("You have selected Narrator Three, Reginald.")
sleep(3)
print("Hooray, you picked me!")
sleep(3)
print("You have selected Narrator Four, Yaxamie.")
sleep(3)
print("You have selected Narrator Five, Tasslehoff.")
sleep(3)
print("Wow, I've never been a narrator before.  This is awesome!")
sleep(3)
print("You have selected Narrator Six, Thadian.")
sleep(3)
print("I'm glad this is a poetry recital because my lute got ruined in a shipwreck.")
sleep(3)
print("You have selcted Narrator Seven, Morgan.")
sleep(3)
print("Are you on Discord yet?")
sleep(3)
print("You have selected Narrator Eight, Patrick.")
sleep(3)
print("One ring to rule them all, my dudes.")
sleep(3)
print("You have selected Narrator Nine, Vincent.")
sleep(3)
print("I am not Vincent van Gogh.  I am just a tribute.")
sleep(3)
print("Let's now go to the choice of genre paths.  Here are your five options.")
sleep(3)
print("One, sea shanties and work songs.")
sleep(3)
print("Two, folk songs.")
sleep(3)
print("Three, songs from musicals.")
sleep(3)
print("Four, children's songs.")
sleep(3)
print("Five, total chaos.")
sleep(3)
print("Type the number of your choice and press Enter.")
sleep(3)
print("Please choose from the provided options.")
sleep(3)
print("You have selected option one, sea shanties and work songs.")
sleep(3)
print("You have selected option two, folk songs.")
sleep(3)
print("You have selected option three, songs from musicals.")
sleep(3)
print("You have selected option four, children's songs.")
sleep(3)
print("You have selected option five, total chaos.")
sleep(3)
# Path One: sea shanties and work songs.
print("Choice One")
print("1     I")
print("2     They")
print("3     We")
print("4     Once")
print("5     Twice")
print("6     Thrice")
print("7     Drunken")
print("8     Farting")
print("9     Stupid")
print("10    Young")
print("11    Old")
print("12    Fat")
print("13    Pirate")
print("14    Teacher")
print("15    Lawyer")
choice = input(print("Type the number of your choice and press Enter:  "))
while True:
    if choice == "1":
        print("You have selected option one, I.")
        break
    elif choice == "2":
        print("You have selected option two, They.")
        break
    elif choice == "3":
        print("You have selected option three, We.")
        break
    elif choice == "4":
        print("You have selected option four, Once.")
        break
    elif choice == "5":
        print("You have selected option five, Twice.")
        break
    elif choice == "6":
        print("You have selected option six, Thrice.")
        break
    elif choice == "7":
        print("You have selected option seven, Drunken.")
        break
    elif choice == "8":
        print("You have selected option eight, Farting.")
        break
    elif choice == "9":
        print("You have selected option nine, Stupid.")
        break
    elif choice == "10":
        print("You have selected option ten, Young.")
        break
    elif choice == "11":
        print("You have selected option eleven, Old.")
        break
    elif choice == "12":
        print("You have selected option twelve, Fat.")
        break
    elif choice == "13":
        print("You have selected option thirteen, Pirate.")
        break
    elif choice == "14":
        print("You have selected option fourteen, Teacher.")
        break
    elif choice == "15":
        print("You have selected option fifteen, Lawyer.")
        break
    else:
        print("Please choose from the provided options.")
        continue
while True:
    if choice == "1":
        print("Choice Two")
        print("1     Old")
        print("2     Tall")
        print("3     Sad")
        break
    if choice == "2":
        print("Choice Two")
        print("1     Old")
        print("2     Tall")
        print("3     Sad")
        break
    if choice == "3":
        print("Choice Two")
        print("1     Old")
        print("2     Tall")
        print("3     Sad")
        break
    while True:
        choice == input(print("Type the number of your choice and press Enter:  "))
        if choice == "1":
            print("You have selected option one, Old.")
            break
        elif choice == "2":
            print("You have selected option two, Tall.")
            break
        elif choice == "3":
            print("You have selected option three, Sad.")
            break
        else:
            print("Please choose from the provided options.")
            continue
while True:
    if choice == "4":
        print("Choice Two")
        print("4     Billy")
        print("5     Enterprise")
        print("6     Carpenter")
        break
    if choice == "5":
        print("Choice Two")
        print("4     Billy")
        print("5     Enterprise")
        print("6     Carpenter")
        break
    if choice == "6":
        print("Choice Two")
        print("4     Billy")
        print("5     Enterprise")
        print("6     Carpenter")
        break
    while True:
        if choice == "4":
            print("You have selected option four, Billy.")
            break
        elif choice == "5":
            print("You have selected option five, Enterprise.")
            break
        elif choice == "6":
            print("You have selected option six, Carpenter.")
            break
        else:
            print("Please choose from the provided options.")
            continue
while True:
    if choice == "7":
        print("Choice Two")
        print("7     Sailor")
        print("8     Bouncer")
        print("9     Painter")
        break
    if choice == "8":
        print("Choice Two")
        print("7     Sailor")
        print("8     Bouncer")
        print("9     Painter")
        break
    if choice == "9":
        print("Choice Two")
        print("7     Sailor")
        print("8     Bouncer")
        print("9     Painter")
        break
while True:
    if choice == "10":
        print("Choice Two")
        print("10    Fellows")
        print("11    Chickens")
        print("12    Farters")
        break
    if choice == "11":
        print("Choice Two")
        print("10    Fellows")
        print("11    Chickens")
        print("12    Farters")
    if choice == "12":
        print("Choice Two")
        print("10    Fellows")
        print("11    Chickens")
        print("12    Farters")
        break
while True:
    if choice == "13":
        print("Choice Two")
        print("13    Me")
        print("14    Her")
        print("15    Them")
        break
    if choice == "14":
        print("Choice Two")
        print("13    Me")
        print("14    Her")
        print("15    Them")
        break
    if choice == "15":
        print("Choice Two")
        print("13    Me")
        print("14    Her")
        print("15    Them")
        break
while True:
    if choice == "1":
        print("Choice Three")
        print("1     Say")
        print("2     Yell")
        print("3     Wish")
        break
    if choice == "2":
        print("Choice Three")
        print("1     Say")
        print("2     Yell")
        print("3     Wish")
        break
    if choice == "3":
        print("Choice Three")
        print("1    Say")
        print("2    Yell")
        print("3    Wish")
        break
while True:
    if choice == "4":
        print("Choice Three")
        print("4     Up")
        print("5     Down")
        print("6     In")
        break
    if choice == "5":
        print("Choice Three")
        print("4     Up")
        print("5     Down")
        print("6     In")
        break
    if choice == "6":
        print("4    Up")
        print("5    Down")
        print("6    In")
        break
while True:
    if choice == "7":
        print("Choice Three")
        print("7     Early")
        print("8     Lately")
        print("9     Never")
        break
    if choice == "8":
        print("Choice Three")
        print("7     Early")
        print("8     Lately")
        print("9     Never")
        break
    if choice == "9":
        print("Choice Three")
        print("7    Early")
        print("8    Lately")
        print("9    Never")
        break
while True:
    if choice == "10":
        print("Choice Three")
        print("10    Sea")
        print("11    News")
        print("12    Game")
        break
    if choice == "11":
        print("Choice Three")
        print("10    Sea")
        print("11    News")
        print("12    Game")
        break
    if choice == "12":
        print("Choice Three")
        print("10    Sea")
        print("11    News")
        print("12    Game")
        break
while True:
    if choice == "13":
        print("Choice Three")
        print("13    Pillage")
        print("14    Sweep")
        print("15    Bake")
        break
    if choice == "14":
        print("Choice Three")
        print("13    Pillage")
        print("14    Sweep")
        print("15    Bake")
        break
    if choice == "15":
        print("13    Pillage")
        print("14    Sweep")
        print("15    Bake")
        break
while True:
    if choice == "1":
        print("Choice Four")
        print("1     Leave")
        print("2     Watch")
        print("3     Trust")
        break
    if choice == "2":
        print("Choice Four")
        print("1     Leave")
        print("2     Watch")
        print("3     Trust")
    if choice == "3":
        print("Choice Four")
        print("1     Leave")
        print("2     Watch")
        print("3     Trust")
        break
while True:
    if choice == "4":
        print("Choice Four")
        print("4     Blow")
        print("5     Sing")
        print("6     Dance")
        break
    if choice == "5":
        print("Choice Four")
        print("4     Blow")
        print("5     Sing")
        print("6     Dance")
        break
    if choice == "6":
        print("Choice Four")
        print("4    Blow")
        print("5    Sing")
        print("6    Dance")
        break
while True:
    if choice == "7":
        print("Choice Four")
        print("7     Morning")
        print("8     Party")
        print("9     Evening")
        break
    if choice == "8":
        print("Choice Four")
        print("7     Morning")
        print("8     Party")
        print("9     Evening")
        break
    if choice == "9":
        print("Choice Four")
        print("7    Morning")
        print("8    Party")
        print("9    Evening")
        break
while True:
    if choice == "10":
        print("Choice Four")
        print("10    Me")
        print("11    You")
        print("12    Down")
        break
    if choice == "11":
        print("Choice Four")
        print("10    Me")
        print("11    You")
        print("12    Down")
        break
    if choice == "12":
        print("Choice Four")
        print("10    Me")
        print("11    You")
        print("12    Down")
        break
while True:
    if choice == "13":
        print("Choice Four")
        print("13    Plunder")
        print("14    Fart")
        print("15    Paint")
        break
    if choice == "14":
        print("Choice Four")
        print("13    Plunder")
        print("14    Fart")
        print("15    Paint")
        break
    if choice == "15":
        print("Choice Four")
        print("13    Plunder")
        print("14    Fart")
        print("15    Paint")
        break 
while True:
    if choice == "1":
        print("Choice Five")
        print("1     Johnny")
        print("2     Timmy")
        print("3     Frodo")
        break
    if choice == "2":
        print("Choice Five")
        print("1     Johnny")
        print("2     Timmy")
        print("3     Frodo")
        break
    if choice == "3":
        print("Choice Five")
        print("1    Johnny")
        print("2    Timmy")
        print("3    Frodo")
        break
while True:
    if choice == "4":
        print("Choice Five")
        print("4     Soon")
        print("5     When")
        print("6     Why")
        break
    if choice == "5":
        print("Choice Five")
        print("4     Soon")
        print("5     When")
        print("6     Why")
        break
    if choice == "6":
        print("Choice Five")
        print("4     Soon")
        print("5     When")
        print("6     Why")
        break
while True:
    if choice == "7":
        print("Choice Five")
        print("7     Brig")
        print("8     Toilets")
        print("9     Farts")
        break
    if choice == "8":
        print("Choice Five")
        print("7     Brig")
        print("8     Toilets")
        print("9     Farts")
        break
    if choice == "9":
        print("7     Brig")
        print("8     Toilets")
        print("9     Farts")
        break
while True:
    if choice == "10":
        print("Choice Five")
        print("10    Blow")
        print("11    Slap")
        print("12    Chase")
        break
    if choice == "11":
        print("Choice Five")
        print("10    Blow")
        print("11    Slap")
        print("12    Chase")
        break
    if choice == "12":
        print("Choice Five")
        print("10    Blow")
        print("11    Slap")
        print("12    Chase")
        break
while True:
    if choice == "13":
        print("Choice Five")
        print("13    Rifle")
        print("14    Vomit")
        print("15    Books")
    if choice == "14":
        print("Choice Five")
        print("13    Rifle")
        print("14    Vomit")
        print("15    Books")
    if choice == "15":
        print("Choice Five")
        print("13    Rifle")
        print("14    Vomit")
        print("15    Books")
        break
while True:
    if choice == "1":
        print("Choice Six")
    if choice == "2":
        print("Choice Six")
    if choice == "3":
        print("Choice Six")
        print("1    Tomorrow")
        print("2    Next Tuesday")
        print("3    On Friday")
while True:
    if choice == "4":
        print("Choice Six")
        print("4     Wellerman")
        print("5     Butterfly")
        print("6     Limousine")
        break
    if choice == "5":
        print("Choice Six")
        print("4     Wellerman")
        print("5     Butterfly")
        print("6     Limousine")
        break
    if choice == "6":
        print("Choice Six")
        print("4    Wellerman")
        print("5    Butterfly")
        print("6    Limousine")
while True:
    if choice == "7":
        print("Choice Six")
        print("7     Rises")
        print("8     Wiggles")
        print("9     Bubbles")
        break
    if choice == "8":
        print("Choice Six")
        print("7     Rises")
        print("8     Wiggles")
        print("9     Bubbles")
        break
    if choice == "9":
        print("Choice Six")
        print("7    Rises")
        print("8    Wiggles")
        print("9    Bubbles")
        break
while True:
    if choice == "10":
        print("Choice Six")
        print("10    Attention")
        print("11    Taxes")
        print("12    Biscuit")
        break
    if choice == "11":
        print("Choice Six")
        print("10    Attention")
        print("11    Taxes")
        print("12    Biscuit")
        break
    if choice == "12":
        print("Choice Six")
        print("10    Attention")
        print("11    Taxes")
        print("12    Biscuit")
        break
while True:
    if choice == "13":
        print("Choice Six")
        print("13    Loot")
        print("14    Hoot")
        print("15    Toot")
        break
    if choice == "14":
        print("Choice Six")
        print("13    Loot")
        print("14    Hoot")
        print("15    Toot")
        break
    if choice == "15":
        print("Choice Six")
        print("13    Loot")
        print("14    Hoot")
        print("15    Toot")
while True:
    if choice == "1":
        print("Choice Seven")
        print("1     Pay")
        print("2     Bell")
        print("3    Fish")
        break
    if choice == "2":
        print("Choice Seven")
        print("1     Pay")
        print("2     Bell")
        print("3     Fish")
        break
    if choice == "3":
        print("Choice Seven")
        print("1    Pay")
        print("2    Bell")
        print("3    Fish")
        break
while True:
    if choice == "4":
        print("Choice Seven")
        print("4     Come")
        print("5     Go")
        print("6     Leave")
    if choice == "5":
        print("Choice Seven")
        print("4     Come")
        print("5     Go")
        print("6     Leave")
    if choice == "6":
        print("Choice Seven")
        print("4     Come")
        print("5     Go")
        print("6     Leave")
while True:
    if choice == "7":
        print("Choice Seven")
        print("7     Clown")
        print("8     Dunce")
        print("9     Crackers")
        break
    if choice == "8":
        print("Choice Seven")
        print("7     Clown")
        print("8     Dunce")
        print("9     Crackers")
        break
    if choice == "9":
        print("Choice Seven")
        print("7    Clown")
        print("8    Dunce")
        print("9    Crackers")
while True:
    if choice == "10":
        print("Choice Seven")
        print("10    Blow")
        print("11    Finish")
        print("12    Take")
        break
    if choice == "11":
        print("Choice Seven")
        print("10    Blow")
        print("11    Finish")
        print("12    Take")
        break
    if choice == "12":
        print("Choice Seven")
        print("10    Blow")
        print("11    Finish")
        print("12    Take")
        break
while True:
    if choice == "13":
        print("Choice Seven")
        print("13    Drink")
        print("14    Eat")
        print("15    Shop")
        break
    if choice == "14":
        print("Choice Seven")
        print("13    Drink")
        print("14    Eat")
        print("15    Shop")
        break
    if choice == "15":
        print("Choice Seven")
        print("13    Drink")
        print("14    Eat")
        print("15    Shop")
        break
while True:
    if choice == "1":
        print("Choice Eight")
        print("1     Long")
        print("2     Short")
        print("3     Wild")
        break
    if choice == "2":
        print("Choice Eight")
        print("1     Long")
        print("2     Short")
        print("3     Wild")
        break
    if choice == "3":
        print("Choice Eight")
        print("1    Long")
        print("2    Short")
        print("3    Wild")
        break
while True:
    if choice == "4":
        print("Choice Eight")
        print("4     Sugar")
        print("5     Twizzlers")
        print("6     Pizza")
        break
    if choice == "5":
        print("Choice Eight")
        print("4     Sugar")
        print("5     Twizzlers")
        print("6     Pizza")
        break
    if choice == "6":
        print("Choice Eight")
        print("4    Sugar")
        print("5    Twizzlers")
        print("6    Pizza")
        break
while True:
    if choice == "7":
        print("Choice Eight")
        print("7     Wash")
        print("8     Drink")
        print("9     Smell")
        break
    if choice == "8":
        print("Choice Eight")
        print("7     Wash")
        print("8     Drink")
        print("9     Smell")
        break
    if choice == "9":
        print("Choice Eight")
        print("7     Wash")
        print("8     Drink")
        print("9     Smell")
        break
while True:
    if choice == "10":
        print("Choice Eight")
        print("10    Deep")
        print("11    Business")
        print("12    Lazy")
        break
    if choice == "11":
        print("Choice Eight")
        print("10    Deep")
        print("11    Business")
        print("12    Lazy")
        break
    if choice == "12":
        print("Choice Eight")
        print("10    Deep")
        print("11    Business")
        print("12    Lazy")
        break
while True:
    if choice == "13":
        print("Choice Eight")
        print("13    Hearties")
        print("14    Homies")
        print("15    Peeps")
        break
    if choice == "14":
        print("Choice Eight")
        print("13    Hearties")
        print("14    Homies")
        print("15    Peeps")
        break
    if choice == "15":
        print("Choice Eight")
        print("13    Hearties")
        print("14    Homies")
        print("15    Peeps")
        break
while True:
    if choice == "1":
        print("Choice Nine")
        print("1     Wind")
        print("2     Food")
        print("3     Smell")
        break
    if choice == "2":
        print("Choice Nine")
        print("1     Wind")
        print("2     Food")
        print("3     Smell")
        break
    if choice == "3":
        print("Choice Nine")
        print("1    Wind")
        print("2    Food")
        print("3    Smell")
        break
while True:
    if choice == "4":
        print("Choice Nine")
        print("4     Tea")
        print("5     T-shirts")
        print("6     Shoes")
        break
    if choice == "5":
        print("Choice Nine")
        print("4     Tea")
        print("5     T-shirts")
        print("6     Shoes")
        break
    if choice == "6":
        print("Choice Nine")
        print("4    Tea")
        print("5    T-shirts")
        print("6    Shoes")
        break
while True:
    if choice == "7":
        print("Choice Nine")
        print("7     Polish")
        print("8     Wipe")
        print("9     Clean")
        break
    if choice == "8":
        print("Choice Nine")
        print("7     Polish")
        print("8     Wipe")
        print("9     Clean")
        break
    if choice == "9":
        print("Choice Nine")
        print("7    Polish")
        print("8    Wipe")
        print("9    Clean")
        break
while True:
    if choice == "10":
        print("Choice Nine")
        print("10    Sailor")
        print("11    Pickle")
        print("12    Fart")
        break
    if choice == "11":
        print("Choice Nine")
        print("10    Sailor")
        print("11    Pickle")
        print("12    Fart")
        break
    if choice == "12":
        print("Choice Nine")
        print("10    Sailor")
        print("11    Pickle")
        print("12    Fart")
        break
while True:
    if choice == "13":
        print("Choice Nine")
        print("13    Yo")
        print("14    Go")
        print("15    No")
        break
    if choice == "14":
        print("Choice Nine")
        pritn("13    Yo")
        print("14    Go")
        print("15    No")
        break
    if choice == "15":
        print("Choice Nine")
        print("13    Yo")
        print("14    Go")
        print("15    No")
        break
while True:
    if choice == "1":
        print("Choice Ten")
        print("1     Foul")
        print("2     Cold")
        print("3     Weird")
        break
    if choice == "2":
        print("Choice Ten")
        print("1     Foul")
        print("2     Cold")
        print("3     Weird")
        break
    if choice == "3":
        print("Choice Ten")
        print("1    Foul")
        print("2    Cold")
        print("3    Weird")
        break
while True:
    if choice == "4":
        print("Choice Ten")
        print("4     Rum")
        print("5     Coke")
        print("6     Prune Juice")
        break
    if choice == "5":
        print("Choice Ten")
        print("4     Rum")
        print("5     Coke")
        print("6     Prune Juice")
        break
    if choice == "6":
        print("Choice Ten")
        print("4     Rum")
        print("5     Coke")
        print("6     Prune Juice")
        break
while True:
    if choice == "7":
        print("Choice Ten")
        print("7     Standing")
        print("8     Vomit")
        print("9     Laundry")
        break
    if choice == "8":
        print("Choice Ten")
        print("7     Standing")
        print("8     Vomit")
        print("9     Laundry")
        break
    if choice == "9":
        print("Choice Ten")
        print("7    Standing")
        print("8    Vomit")
        print("9    Laundry")
        break
while True:
    if choice == "10":
        print("Choice Ten")
        print("10    Hong Kong")
        print("11    The Bronx")
        print("12    L.A.")
        break
    if choice == "11":
        print("Choice Ten")
        print("10    Hong Kong")
        print("11    The Bronx")
        print("12    L.A.")
        break
    if choice == "12":
        print("Choice Ten")
        print("10    Hong Kong")
        print("11    The Bronx")
        print("12    L.A.")
        break
while True:
    if choice == "13": 
        print("Choice Ten")
        print("13    Kidnap")
        print("14    Play")
        print("15    Buy")
        break
    if choice == "14":
        print("Choice Ten")
        print("13    Kidnap")
        print("14    Play")
        print("15    Buy")
        break
    if choice == "15":
        print("Choice Ten")
        print("13    kidnap")
        print("14    play")
        print("15    buy")
        break
while True:
    if choice == "1":
        print("Choice Eleven")
        print("1     None")
        print("2     All")
        print("3     Some")
        break
    if choice == "2":
        print("Choice Eleven")
        print("1     None")
        print("2     All")
        print("3     Some")
        break
    if choice == "3":
        print("Choice Eleven")
        print("1    None")
        print("2    All")
        print("3    Some")
        break
while True:
    if choice == "4":
        print("Choice Eleven")
        print("4     Tonguing")
        print("5     Singing")
        print("6     Mopping")
    if choice == "5":
        print("Choice Eleven")
        print("4     Tonguing")
        print("5     Singing")
        print("6     Mopping")
        break
    if choice == "6":
        print("Choice Eleven")
        print("4    Tonguing")
        print("5    Singing")
        print("6    Mopping")
        break
while True:
    if choice == "7":
        print("Choice Eleven")
        print("7     Leave")
        print("8     Breakfast")
        print("9     Pots")
        break
    if choice == "8":
        print("Choice Eleven")
        print("7     Leave")
        print("8     Breakfast")
        print("9     Pots")
        break
    if choice == "9":
        print("Choice Eleven")
        print("7    Leave")
        print("8    Breakfast")
        print("9    Pots")
        break
while True:
    if choice == "10":
        print("Choice Eleven")
        print("10    Drink")
        print("11    Cow")
        print("12    Toilet")
        break
    if choice == "11":
        print("Choice Eleven")
        print("10    Drink")
        print("11    Cow")
        print("12    Toilet")
        break
    if choice == "12":
        print("Choice Eleven")
        print("10    Drink")
        print("11    Cow")
        print("12    Toilet")
        break
while True:
    if choice == "13":
        print("Choice Eleven")
        print("13    Hoot")
        print("14    Crap")
        print("15    Boot")
        break
    if choice == "14":
        print("Choice Eleven")
        print("13    Hoot")
        print("14    Crap")
        print("15    Boot")
        break
    if choice == "15":
        print("Choice Eleven")
        print("13    Hoot")
        print("14    Crap")
        print("15    Boot")
        break
# Path Two:  folk songs
while True:
    print("Choice One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
while True:
    print("Choice Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13") 
    print("14")
    print("15")
while True:
    print("Choice Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Six")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Seven")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eight")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Nine")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Ten")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eleven")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice One Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice One Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice One Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice One Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice One Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Two Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Two Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Two Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Two Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Two Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Three Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Three Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Three Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Three Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Three Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Four Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Four Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Four Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Four Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Four Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Five Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Five Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Five Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Five Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Five Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Six Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Six Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Six Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Six Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Six Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Seven Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Seven Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Seven Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Seven Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Seven Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Eight Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eight Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eight Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eight Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eight Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Nine Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Nine Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Nine Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Nine Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Nine Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Ten Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Ten Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Ten Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Ten Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print*("Choice Ten Part Five")
    print("1")
    print("2")
    print("3")
    print("4")
    print("Choice Eleven Part One")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eleven Part Two")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eleven Part Three")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eleven Part Four")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("Choice Eleven Part Five")
    print("1")
    print("2")
    print("3")
    print("4")