import pygame
from tkinter import *
import tkinter as tk
import time
pygame.init()
pygame.mixer.music.load("Eight_Bit_Adventure.mp3")
pygame.mixer.music.play()
pycharm_default_font = ("JetBrains Mono", 13)
time.sleep(5)


def window1():
    window = Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger01 = PhotoImage(file="01.png")
    messenger02 = PhotoImage(file="02.png")
    messenger01_background = Label(window, image=messenger01)
    messenger02_background = Label(window, image=messenger02)
    messenger01_background.grid(row=1, column=1, padx=50, pady=50)
    messenger02_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window2():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger03 = PhotoImage(file="03.png")
    messenger04 = PhotoImage(file="04.png")
    messenger03_background = Label(window, image=messenger03)
    messenger04_background = Label(window, image=messenger04)
    messenger03_background.grid(row=1, column=1, padx=50, pady=50)
    messenger04_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window3():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger05 = PhotoImage(file="05.png")
    messenger06 = PhotoImage(file="06.png")
    messenger05_background = Label(window, image=messenger05)
    messenger06_background = Label(window, image=messenger06)
    messenger05_background.grid(row=1, column=1, padx=50, pady=50)
    messenger06_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window4():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger07 = PhotoImage(file="07.png")
    messenger08 = PhotoImage(file="08.png")
    messenger07_background = Label(window, image=messenger07)
    messenger08_background = Label(window, image=messenger08)
    messenger07_background.grid(row=1, column=1, padx=50, pady=50)
    messenger08_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window5():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger09 = PhotoImage(file="09.png")
    messenger10 = PhotoImage(file="10.png")
    messenger09_background = Label(window, image=messenger09)
    messenger10_background = Label(window, image=messenger10)
    messenger09_background.grid(row=1, column=1, padx=50, pady=50)
    messenger10_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window6():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger11 = PhotoImage(file="11.png")
    messenger12 = PhotoImage(file="12.png")
    messenger11_background = Label(window, image=messenger11)
    messenger12_background = Label(window, image=messenger12)
    messenger11_background.grid(row=1, column=1, padx=50, pady=50)
    messenger12_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window7():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger13 = PhotoImage(file="13.png")
    messenger14 = PhotoImage(file="14.png")
    messenger13_background = Label(window, image=messenger13)
    messenger14_background = Label(window, image=messenger14)
    messenger13_background.grid(row=1, column=0, columnspan=50)
    messenger14_background.grid(row=1, column=0, columnspan=50)
    polygamy1 = PhotoImage(file="wedding.png")
    polygamy2 = PhotoImage(file="wedding.png")
    polygamy3 = PhotoImage(file="wedding.png")
    polygamy4 = PhotoImage(file="wedding.png")
    polygamy5 = PhotoImage(file="wedding.png")
    polygamy6 = PhotoImage(file="wedding.png")
    polygamy7 = PhotoImage(file="wedding.png")
    polygamy8 = PhotoImage(file="wedding.png")
    polygamy9 = PhotoImage(file="wedding.png")
    polygamy10 = PhotoImage(file="wedding.png")
    polygamy11 = PhotoImage(file="wedding.png")
    polygamy12 = PhotoImage(file="wedding.png")
    polygamy13 = PhotoImage(file="wedding.png")
    polygamy14 = PhotoImage(file="wedding.png")
    polygamy15 = PhotoImage(file="wedding.png")
    polygamy16 = PhotoImage(file="wedding.png")
    polygamy17 = PhotoImage(file="wedding.png")
    polygamy18 = PhotoImage(file="wedding.png")
    polygamy19 = PhotoImage(file="wedding.png")
    polygamy20 = PhotoImage(file="wedding.png")
    polygamy21 = PhotoImage(file="wedding.png")
    polygamy22 = PhotoImage(file="wedding.png")
    polygamy23 = PhotoImage(file="wedding.png")
    polygamy24 = PhotoImage(file="wedding.png")
    polygamy25 = PhotoImage(file="wedding.png")
    polygamy26 = PhotoImage(file="wedding.png")
    polygamy27 = PhotoImage(file="wedding.png")
    polygamy28 = PhotoImage(file="wedding.png")
    polygamy29 = PhotoImage(file="wedding.png")
    polygamy30 = PhotoImage(file="wedding.png")
    polygamy31 = PhotoImage(file="wedding.png")
    polygamy32 = PhotoImage(file="wedding.png")
    polygamy1pic = Label(window, image=polygamy1)
    polygamy2pic = Label(window, image=polygamy2)
    polygamy3pic = Label(window, image=polygamy3)
    polygamy4pic = Label(window, image=polygamy4)
    polygamy5pic = Label(window, image=polygamy5)
    polygamy6pic = Label(window, image=polygamy6)
    polygamy7pic = Label(window, image=polygamy7)
    polygamy8pic = Label(window, image=polygamy8)
    polygamy9pic = Label(window, image=polygamy9)
    polygamy10pic = Label(window, image=polygamy10)
    polygamy11pic = Label(window, image=polygamy11)
    polygamy12pic = Label(window, image=polygamy12)
    polygamy13pic = Label(window, image=polygamy13)
    polygamy14pic = Label(window, image=polygamy14)
    polygamy15pic = Label(window, image=polygamy15)
    polygamy16pic = Label(window, image=polygamy16)
    polygamy17pic = Label(window, image=polygamy17)
    polygamy18pic = Label(window, image=polygamy18)
    polygamy19pic = Label(window, image=polygamy19)
    polygamy20pic = Label(window, image=polygamy20)
    polygamy21pic = Label(window, image=polygamy21)
    polygamy22pic = Label(window, image=polygamy22)
    polygamy23pic = Label(window, image=polygamy23)
    polygamy24pic = Label(window, image=polygamy24)
    polygamy25pic = Label(window, image=polygamy25)
    polygamy26pic = Label(window, image=polygamy26)
    polygamy27pic = Label(window, image=polygamy27)
    polygamy28pic = Label(window, image=polygamy28)
    polygamy29pic = Label(window, image=polygamy29)
    polygamy30pic = Label(window, image=polygamy30)
    polygamy31pic = Label(window, image=polygamy31)
    polygamy32pic = Label(window, image=polygamy32)
    polygamy1pic.grid(row=2, column=1)
    polygamy2pic.grid(row=2, column=2)
    polygamy3pic.grid(row=2, column=3)
    polygamy4pic.grid(row=2, column=4)
    polygamy5pic.grid(row=2, column=5)
    polygamy6pic.grid(row=2, column=6)
    polygamy7pic.grid(row=2, column=7)
    polygamy8pic.grid(row=2, column=8)
    polygamy9pic.grid(row=3, column=1)
    polygamy10pic.grid(row=3, column=2)
    polygamy11pic.grid(row=3, column=3)
    polygamy12pic.grid(row=3, column=4)
    polygamy13pic.grid(row=3, column=5)
    polygamy14pic.grid(row=3, column=6)
    polygamy15pic.grid(row=3, column=7)
    polygamy16pic.grid(row=3, column=8)
    polygamy17pic.grid(row=4, column=1)
    polygamy18pic.grid(row=4, column=2)
    polygamy19pic.grid(row=4, column=3)
    polygamy20pic.grid(row=4, column=4)
    polygamy21pic.grid(row=4, column=5)
    polygamy22pic.grid(row=4, column=6)
    polygamy23pic.grid(row=4, column=7)
    polygamy24pic.grid(row=4, column=8)
    polygamy25pic.grid(row=5, column=1)
    polygamy26pic.grid(row=5, column=2)
    polygamy27pic.grid(row=5, column=3)
    polygamy28pic.grid(row=5, column=4)
    polygamy29pic.grid(row=5, column=5)
    polygamy30pic.grid(row=5, column=6)
    polygamy31pic.grid(row=5, column=7)
    polygamy32pic.grid(row=5, column=8)

    polygamy1pic.config(image=polygamy1)
    window.after(167, lambda: polygamy2pic.config(image=polygamy2))
    window.after(334, lambda: polygamy3pic.config(image=polygamy3))
    window.after(501, lambda: polygamy4pic.config(image=polygamy4))
    window.after(668, lambda: polygamy5pic.config(image=polygamy5))
    window.after(835, lambda: polygamy6pic.config(image=polygamy6))
    window.after(1002, lambda: polygamy7pic.config(image=polygamy7))
    window.after(1169, lambda: polygamy8pic.config(image=polygamy8))
    window.after(1336, lambda: polygamy9pic.config(image=polygamy9))
    window.after(1503, lambda: polygamy10pic.config(image=polygamy10))
    window.after(1670, lambda: polygamy11pic.config(image=polygamy11))
    window.after(1837, lambda: polygamy12pic.config(image=polygamy12))
    window.after(2004, lambda: polygamy13pic.config(image=polygamy13))
    window.after(2171, lambda: polygamy14pic.config(image=polygamy14))
    window.after(2338, lambda: polygamy15pic.config(image=polygamy15))
    window.after(2505, lambda: polygamy16pic.config(image=polygamy16))
    window.after(2672, lambda: polygamy17pic.config(image=polygamy17))
    window.after(2839, lambda: polygamy18pic.config(image=polygamy18))
    window.after(3006, lambda: polygamy19pic.config(image=polygamy19))
    window.after(3173, lambda: polygamy20pic.config(image=polygamy20))
    window.after(3340, lambda: polygamy21pic.config(image=polygamy21))
    window.after(3507, lambda: polygamy22pic.config(image=polygamy22))
    window.after(3674, lambda: polygamy23pic.config(image=polygamy23))
    window.after(3841, lambda: polygamy24pic.config(image=polygamy24))
    window.after(4008, lambda: polygamy25pic.config(image=polygamy25))
    window.after(4175, lambda: polygamy26pic.config(image=polygamy26))
    window.after(4342, lambda: polygamy27pic.config(image=polygamy27))
    window.after(4509, lambda: polygamy28pic.config(image=polygamy28))
    window.after(4676, lambda: polygamy29pic.config(image=polygamy29))
    window.after(4843, lambda: polygamy30pic.config(image=polygamy30))
    window.after(5010, lambda: polygamy31pic.config(image=polygamy31))
    window.after(5177, lambda: polygamy32pic.config(image=polygamy32))


    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window8():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    messenger15 = PhotoImage(file="15.png")
    messenger16 = PhotoImage(file="16.png")
    messenger15_background = Label(window, image=messenger15)
    messenger16_background = Label(window, image=messenger16)
    messenger15_background.grid(row=1, column=1, padx=50, pady=50)
    messenger16_background.grid(row=1, column=2, padx=50, pady=50)
    window.after(5360, lambda: window.destroy())
    window.mainloop()


def window9():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    wtf = PhotoImage(file="17.png")
    wtf_background = Label(window, image=wtf)
    wtf_background.grid(row=1, column=0, padx=50, pady=50)
    window.after(2000, lambda: pygame.mixer.music.fadeout(3360))
    window.after(5360, lambda: pygame.mixer.music.unload())
    window.after(5365, lambda: window.destroy())
    window.mainloop()


def window10():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="", bg="black")
    label.grid(row=0, column=0)
    interviewscreen1 = PhotoImage(file="interviewscreen1.png")
    interviewscreen2 = PhotoImage(file="interviewscreen2.png")
    interviewscreen3 = PhotoImage(file="interviewscreen3.png")
    interviewscreen4 = PhotoImage(file="interviewscreen4.png")
    interviewscreen5 = PhotoImage(file="interviewscreen5.png")
    interviewscreen_background = Label(window, image=interviewscreen1)
    interviewscreen_background.grid(row=0, column=0)
    interviewscreen_background.after(10000, lambda: interviewscreen_background.config(image=interviewscreen2))
    interviewscreen_background.after(16000, lambda: interviewscreen_background.config(image=interviewscreen3))
    interviewscreen_background.after(23000, lambda: interviewscreen_background.config(image=interviewscreen4))
    interviewscreen_background.after(29000, lambda: interviewscreen_background.config(image=interviewscreen5))
    lex = PhotoImage(file="LexFridman.png")
    lex_background = Label(window, image=lex)
    lex_background.grid(row=0, column=1, padx=50, pady=50)
    lex_background.after(8080, lambda: lex_background.destroy())
    guido = PhotoImage(file="GuidovanRossum.png")
    guido_background = Label(window, image=guido)
    guido_background.after(8080, lambda: guido_background.grid(row=0, column=1, padx=50, pady=50))
    window.after(44000, lambda: pygame.mixer.music.unload())
    window.after(44000, lambda: window.destroy())
    window.mainloop()


def window11():
    window = tk.Tk()
    width = window.winfo_screenwidth()
    height = window.winfo_screenheight()
    window.geometry("%dx%d" % (width, height))
    window.title("Digital Bard")
    window.config(bg="black")
    label = tk.Label(window, text="")
    label.grid(row=0, column=0)
    bardwithlute = PhotoImage(file="digitalbardbg.png")
    bardwithlute_background = Label(window, image=bardwithlute)
    bardwithlute_background.grid(row=0, column=0)
    window.mainloop()


window1()
window2()
window3()
window4()
window5()
window6()
window7()
window8()
window9()
pygame.mixer.music.unload()
pygame.mixer.music.load("Interview.mp3")
pygame.mixer.music.play()
window10()
pygame.mixer.music.load("scarborough_fair.mp3")
pygame.mixer.music.play(-1)
window11()
